version: '3.7'

services:
    r-fts:
        container_name: r-fts-container
        image: r-fts:latest
        build:
            context: .
            dockerfile: Dockerfile
            args:
                HOME: /home/fts/
        volumes:
        - '.:/home/fts'
