version: '3.7'

services:
    r-fts:
        container_name: r-fts-container
        image: r-fts:latest
        build:
            context: .
            dockerfile: Dockerfile
            args:
                HOME: /home/fts/
        volumes:
        - '${PROJECT_FOLDER}:/home/fts/app/'
        - '${PROJECT_DATA}:/home/fts/data/'
        ports:
        - '0.0.0.0:8888:8888'
        command: jupyter-lab --ip 0.0.0.0 --no-browser --allow-root
