install.packages("dplyr",  repos = 'https://cloud.r-project.org')
install.packages("rgl", repos='http://cran.rstudio.com/')
install.packages("fNonlinear", repos='http://cran.rstudio.com/')
install.packages("ppclust",  repos='http://cran.rstudio.com/')
install.packages("EMD", repos='http://cran.rstudio.com/')
install.packages("tseriesChaos", repos='http://cran.rstudio.com/')
install.packages("TSdist",  repos='http://cran.rstudio.com/')
install.packages("Metrics", repos='http://cran.rstudio.com/')
install.packages("beepr", repos='http://cran.rstudio.com/')

